state_codes = {
  'atlanta':['13'],
  'austin':['48'],
  'baltimore':['24'],
  'bham':['01'],
  'boston':['25'],
  'buffalo':['36'],
  'charlotte':['37'],
  'chicago':['17'],
  'cincinnati':['39'],
  'cleveland':['39'],
  'columbus':['39'],
  'dallas': ['48'],
  'denver': ['08'],
  'detroit': ['26'],
  'hartford': ['09'],
  'houston': ['48'],
  'indianapolis': ['18'],
  'inlandempire': ['06'],
  'jacksonville': ['12'],
  'kansascity': ['29','20'],
  'lasvegas': ['32'],
  'losangeles': ['06'],
  'louisville':['21'],
  'memphis':['47'],
  'miami':['12'],
  'milwaukee':['55'],
  'minneapolis':['27'],
  'muncie':['18'],
  'nashville':['47'],
  'newjersey':['34'],
  'newyork':['36','34'],
  'norfolk':['51'],
  'oklahomacity':['40'],
  'orangecounty':['06'],
  'orlando':['12'],
  'philadelphia':['42','34','10'],
  'phoenix':['04'],
  'pittsburgh':['42'],
  'portland':['41'],
  'providence':['44'],
  'raleigh':['37'],
  'richmond':['51'],
  'sacramento':['06'],
  'saltlakecity':['49'],
  'sanantonio':['48'],
  'sandiego':['06'],
  'sanmarcos':['48'],
  'seattle':['53'],
  'sfbay':['06'],
  'stlouis':['29'],
  'tampa':['12'],
  'washingtondc':['11','51','24'],
}