#!/bin/bash
#SBATCH -A p31502               # Allocation
#SBATCH -p normal               # Queue
#SBATCH -t 20:00:00             # Walltime/duration of the job
#SBATCH -N 1                    # Number of Nodes
#SBATCH --mem=18G               # Memory per node in GB needed for a job. Also see --mem-per-cpu
#SBATCH --ntasks-per-node=6     # Number of Cores (Processors)
#SBATCH --job-name="doing initial craigslist scrape"       # Name of job

/projects/p31502/projects/craigslist/scripts/craig_env_runner 

python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("atlanta", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/atlanta_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("austin", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/austin_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("baltimore", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/baltimore_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("bham", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/bham_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("boston", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/boston_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("buffalo", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/buffalo_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("niagara", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/niagara_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("charlotte", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/charlotte_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("chicago", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/chicago_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("cincinnati", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/cincinnati_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("cleveland", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/cleveland_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("columbus", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/columbus_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("dallas", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/dallas_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("denver", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/denver_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("detroit", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/detroit_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("hartford", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/hartford_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("houston", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/houston_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("indianapolis", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/indianapolis_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("muncie", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/muncie.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("jacksonville", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/jacksonville_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("kansascity", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/kansascity_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("lasvegas", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/lasvegas_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("losangeles", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/losangeles_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("orangecounty", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/orangecounty_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("louisville", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/louisville_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("memphis", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/memphis_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("miami", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/miami_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("milwaukee", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/milwaukee_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("minneapolis", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/minneapolis_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("nashville", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/nashville_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("neworleans", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/neworleans_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("newyork", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/newyork_out.out &
# watertown scrape is maybe too much?
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("watertown", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/watertown_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("newjersey", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/newjersey_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("oklahomacity", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/oklahomacity_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("orlando", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/orlando_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("philadelphia", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/philadelphia_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("phoenix", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/phoenix_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("pittsburgh", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/pittsburgh_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("portland", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/portland_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("providence", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/providence_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("raleigh", filepath="../html")'  > /projects/p31502/projects/craigslist/scripts/outfiles/raleigh_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("richmond", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/richmond_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("inlandempire", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/inlandempire_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("sacramento", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/sacramento_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("saltlakecity", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/saltlakecity_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("sanantonio", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/sanantonio_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("sanmarcos", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/sanmarcos_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("sandiego", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/sandiego_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("sfbay", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/sfbay_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("seattle", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/seattle_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("stlouis", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/stlouis_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("tampa", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/tampa_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("stpetersburg", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/stpetersburg_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("norfolk", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/norfolk_out.out &
python -c 'import sys; sys.path.append("/projects/p31502/projects/craigslist/"); from cronable_scraping import *; do_initial_scrape("washingtondc", filepath="../html")' > /projects/p31502/projects/craigslist/scripts/outfiles/washingtondc_out.out &
